# Project: C Text Editor
# Makefile created by Dev-C++ 5.5.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../outputs/main.o ../outputs/exceptio.o ../outputs/genlib.o ../outputs/graphics.o ../outputs/linkedlist.o ../outputs/random.o ../outputs/simpio.o ../outputs/strlib.o ../outputs/textStructure.o ../outputs/blockList.o ../outputs/fileSystem.o
LINKOBJ  = ../outputs/main.o ../outputs/exceptio.o ../outputs/genlib.o ../outputs/graphics.o ../outputs/linkedlist.o ../outputs/random.o ../outputs/simpio.o ../outputs/strlib.o ../outputs/textStructure.o ../outputs/blockList.o ../outputs/fileSystem.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc -mwindows
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"../libgraphics"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.7.2/include/c++" -I"../libgraphics"
BIN      = "../C Text Editor.exe"
CXXFLAGS = $(CXXINCS) -Wall
CFLAGS   = $(INCS) -Wall -std=c99
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

../outputs/main.o: ../source/main.c
	$(CC) -c ../source/main.c -o ../outputs/main.o $(CFLAGS)

../outputs/exceptio.o: ../libgraphics/exceptio.c
	$(CC) -c ../libgraphics/exceptio.c -o ../outputs/exceptio.o $(CFLAGS)

../outputs/genlib.o: ../libgraphics/genlib.c
	$(CC) -c ../libgraphics/genlib.c -o ../outputs/genlib.o $(CFLAGS)

../outputs/graphics.o: ../libgraphics/graphics.c
	$(CC) -c ../libgraphics/graphics.c -o ../outputs/graphics.o $(CFLAGS)

../outputs/linkedlist.o: ../libgraphics/linkedlist.c
	$(CC) -c ../libgraphics/linkedlist.c -o ../outputs/linkedlist.o $(CFLAGS)

../outputs/random.o: ../libgraphics/random.c
	$(CC) -c ../libgraphics/random.c -o ../outputs/random.o $(CFLAGS)

../outputs/simpio.o: ../libgraphics/simpio.c
	$(CC) -c ../libgraphics/simpio.c -o ../outputs/simpio.o $(CFLAGS)

../outputs/strlib.o: ../libgraphics/strlib.c
	$(CC) -c ../libgraphics/strlib.c -o ../outputs/strlib.o $(CFLAGS)

../outputs/textStructure.o: ../source/textStructure.c
	$(CC) -c ../source/textStructure.c -o ../outputs/textStructure.o $(CFLAGS)

../outputs/blockList.o: ../source/blockList.c
	$(CC) -c ../source/blockList.c -o ../outputs/blockList.o $(CFLAGS)

../outputs/fileSystem.o: ../source/fileSystem.c
	$(CC) -c ../source/fileSystem.c -o ../outputs/fileSystem.o $(CFLAGS)
