# Project: BlockChain Editor
# Makefile created by Dev-C++ 5.5.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../outputs/main.o ../outputs/exceptio.o ../outputs/genlib.o ../outputs/graphics.o ../outputs/linkedlist.o ../outputs/random.o ../outputs/simpio.o ../outputs/strlib.o ../outputs/textStructure.o ../outputs/fileSystem.o ../outputs/blockList.o ../outputs/fileSystemCore.o ../outputs/explorerCore.o ../outputs/dictionaryList.o ../outputs/myGUI.o ../outputs/blocklistInitor.o ../outputs/controller.o ../outputs/editorCore.o ../outputs/imageStructure.o ../outputs/imgui.o
LINKOBJ  = ../outputs/main.o ../outputs/exceptio.o ../outputs/genlib.o ../outputs/graphics.o ../outputs/linkedlist.o ../outputs/random.o ../outputs/simpio.o ../outputs/strlib.o ../outputs/textStructure.o ../outputs/fileSystem.o ../outputs/blockList.o ../outputs/fileSystemCore.o ../outputs/explorerCore.o ../outputs/dictionaryList.o ../outputs/myGUI.o ../outputs/blocklistInitor.o ../outputs/controller.o ../outputs/editorCore.o ../outputs/imageStructure.o ../outputs/imgui.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc -mwindows
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"../libgraphics" -I"../header" -I"../simpleGUI"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.7.2/include/c++" -I"../libgraphics" -I"../header" -I"../simpleGUI"
BIN      = "../C Text Editor.exe"
CXXFLAGS = $(CXXINCS) -Wall
CFLAGS   = $(INCS) -Wall -std=c99
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

../outputs/main.o: ../source/main.c
	$(CC) -c ../source/main.c -o ../outputs/main.o $(CFLAGS)

../outputs/exceptio.o: ../libgraphics/exceptio.c
	$(CC) -c ../libgraphics/exceptio.c -o ../outputs/exceptio.o $(CFLAGS)

../outputs/genlib.o: ../libgraphics/genlib.c
	$(CC) -c ../libgraphics/genlib.c -o ../outputs/genlib.o $(CFLAGS)

../outputs/graphics.o: ../libgraphics/graphics.c
	$(CC) -c ../libgraphics/graphics.c -o ../outputs/graphics.o $(CFLAGS)

../outputs/linkedlist.o: ../libgraphics/linkedlist.c
	$(CC) -c ../libgraphics/linkedlist.c -o ../outputs/linkedlist.o $(CFLAGS)

../outputs/random.o: ../libgraphics/random.c
	$(CC) -c ../libgraphics/random.c -o ../outputs/random.o $(CFLAGS)

../outputs/simpio.o: ../libgraphics/simpio.c
	$(CC) -c ../libgraphics/simpio.c -o ../outputs/simpio.o $(CFLAGS)

../outputs/strlib.o: ../libgraphics/strlib.c
	$(CC) -c ../libgraphics/strlib.c -o ../outputs/strlib.o $(CFLAGS)

../outputs/textStructure.o: ../source/textStructure.c
	$(CC) -c ../source/textStructure.c -o ../outputs/textStructure.o $(CFLAGS)

../outputs/fileSystem.o: ../source/fileSystem.c
	$(CC) -c ../source/fileSystem.c -o ../outputs/fileSystem.o $(CFLAGS)

../outputs/blockList.o: ../source/blockList.c
	$(CC) -c ../source/blockList.c -o ../outputs/blockList.o $(CFLAGS)

../outputs/fileSystemCore.o: ../source/fileSystemCore.c
	$(CC) -c ../source/fileSystemCore.c -o ../outputs/fileSystemCore.o $(CFLAGS)

../outputs/explorerCore.o: ../source/explorerCore.c
	$(CC) -c ../source/explorerCore.c -o ../outputs/explorerCore.o $(CFLAGS)

../outputs/dictionaryList.o: ../source/dictionaryList.c
	$(CC) -c ../source/dictionaryList.c -o ../outputs/dictionaryList.o $(CFLAGS)

../outputs/myGUI.o: ../source/myGUI.c
	$(CC) -c ../source/myGUI.c -o ../outputs/myGUI.o $(CFLAGS)

../outputs/blocklistInitor.o: ../source/blocklistInitor.c
	$(CC) -c ../source/blocklistInitor.c -o ../outputs/blocklistInitor.o $(CFLAGS)

../outputs/controller.o: ../source/controller.c
	$(CC) -c ../source/controller.c -o ../outputs/controller.o $(CFLAGS)

../outputs/editorCore.o: ../source/editorCore.c
	$(CC) -c ../source/editorCore.c -o ../outputs/editorCore.o $(CFLAGS)

../outputs/imageStructure.o: ../source/imageStructure.c
	$(CC) -c ../source/imageStructure.c -o ../outputs/imageStructure.o $(CFLAGS)

../outputs/imgui.o: ../simpleGUI/imgui.c
	$(CC) -c ../simpleGUI/imgui.c -o ../outputs/imgui.o $(CFLAGS)
